export const businessRulesConfig = {
  mealTypes: ["colazione", "pranzo", "merenda", "cena"] as const,
  allowedFeedingStyles: ["classico", "autosvezzamento", "misto"] as const,
  ageStageRules: {
    under6: "Prima dei 6 mesi il focus resta sul latte; proporre solo indicazioni prudenti e confronto con pediatra.",
    from6To8: "Consistenze molto morbide: creme lisce, vellutate, alimenti schiacciati.",
    from8To10: "Progressione graduale: piccoli pezzi morbidi e facilmente gestibili.",
    from10To12: "Maggiore varietà mantenendo sicurezza, consistenze adatte e supervisione.",
    from12To24: "Pasti completi bilanciati e progressiva autonomia.",
    over24: "Composizione piatto aggiornata: 2/4 verdure, 1/4 carboidrati, 1/4 proteine + grassi buoni.",
  },
  balancedPlate: {
    under24Months: {
      carbsRatio: "2/4",
      proteinsRatio: "1/4",
      vegetablesRatio: "1/4",
      healthyFats: "olio extravergine d'oliva a crudo",
    },
    over24Months: {
      vegetablesRatio: "2/4",
      carbsRatio: "1/4",
      proteinsRatio: "1/4",
      healthyFats: "piccola quota di grassi buoni (olio extravergine d'oliva a crudo)",
    },
  },
  portionGuidance: {
    text: "Tutte le dosi devono essere pensate per 1 solo bambino, con porzioni piccole e prudenti: cereali secchi circa 15-30 g, proteine circa 20-40 g, verdura o frutta circa 30-80 g, liquidi circa 100-150 ml, yogurt circa 80 g.",
    maxThresholds: {
      grams: 150,
      milliliters: 180,
      tablespoons: 3,
      teaspoons: 2,
      pieces: 2,
    },
  },
  ingredientGroups: {
    carbs: [
      "pasta",
      "riso",
      "farro",
      "orzo",
      "avena",
      "miglio",
      "quinoa",
      "patata",
      "patate",
      "semolino",
      "cous cous",
    ],
    proteins: [
      "carne",
      "manzo",
      "pollo",
      "tacchino",
      "pesce",
      "salmone",
      "merluzzo",
      "uovo",
      "uova",
      "ricotta",
      "formaggio fresco",
      "robiola",
      "legumi",
      "lenticchie",
      "ceci",
      "piselli",
      "fagioli",
    ],
    vegetables: [
      "zucchine",
      "carote",
      "zucca",
      "broccoli",
      "cavolfiore",
      "bietola",
      "spinaci",
      "pomodoro",
      "pomodorini",
      "verdure",
      "fagiolini",
      "melanzane",
    ],
    fruits: ["pera", "banana", "mela", "mela cotta", "frutta"],
    healthyFats: ["olio evo", "olio extravergine", "olio extravergine d'oliva"],
  },
  forbidden: {
    always: [
      "sale aggiunto",
      "zucchero",
      "zuccheri aggiunti",
      "dolcificante",
      "dolcificanti",
      "miele",
      "caramelle",
      "popcorn",
      "frutta secca intera",
      "chicchi duri",
    ],
    chokingRisk: ["frutta secca intera", "popcorn", "caramelle", "chicchi duri"],
    roundFoods: ["uva", "pomodorini"],
    cylindricalFoods: ["carota", "carote", "zucchina", "zucchine"],
    hardFoods: ["mela cruda", "carota cruda"],
  },
  exclusionExpansionGroups: {
    carne: ["carne", "manzo", "vitello", "pollo", "tacchino", "maiale", "coniglio"],
    legumi: ["legumi", "lenticchie", "ceci", "piselli", "fagioli", "cannellini", "borlotti"],
    verdure: [
      "verdure",
      "zucchine",
      "carote",
      "zucca",
      "broccoli",
      "cavolfiore",
      "bietola",
      "spinaci",
      "pomodoro",
      "pomodorini",
      "fagiolini",
      "melanzane",
    ],
    cereali: ["cereali", "avena", "farro", "orzo", "miglio", "quinoa", "semolino", "pasta", "riso"],
    frutta: ["frutta", "pera", "banana", "mela", "mela cotta"],
    latticini: [
      "latticini",
      "latte",
      "latte vaccino",
      "yogurt",
      "formaggio",
      "formaggi",
      "formaggio fresco",
      "formaggi freschi",
      "ricotta",
      "robiola",
      "stracchino",
      "mozzarella",
      "parmigiano",
      "grana",
      "primo sale",
      "fiocchi di latte",
    ],
    uovo: ["uovo", "uova", "frittata"],
    pesce: ["pesce", "merluzzo", "salmone", "orata", "platessa", "trota", "nasello"],
    fruttaSecca: [
      "frutta secca",
      "frutta secca intera",
      "arachidi",
      "mandorle",
      "noci",
      "nocciole",
      "pistacchi",
      "anacardi",
    ],
    glutine: ["glutine", "grano", "frumento", "semolino", "orzo", "farro", "pasta", "pane"],
  },
  safeCutRules: [
    "I cibi tondi vanno proposti in quarti/spicchi (es. uva, pomodorini).",
    "I cibi cilindrici vanno proposti a bastoncino o in taglio longitudinale (es. carote, zucchine).",
    "I cibi duri vanno cotti, grattugiati o ridotti in crema (es. mela cruda, carota cruda).",
  ],
  proteinFrequencyWeekly: {
    carneRossa: "1 volta a settimana",
    carneBianca: "2 volte a settimana",
    pesce: "2 volte a settimana",
    uova: "1-2 volte a settimana",
    legumi: "4-5 volte a settimana",
    formaggiFreschi: "1-2 volte a settimana",
  },
  proteinCategoryKeywords: {
    carneRossa: ["carne rossa", "manzo", "vitello"],
    carneBianca: ["carne bianca", "pollo", "tacchino", "coniglio"],
    pesce: ["pesce", "salmone", "merluzzo", "orata", "platessa", "trota", "nasello"],
    uova: ["uovo", "uova", "frittata"],
    legumi: ["legumi", "lenticchie", "ceci", "piselli", "fagioli", "cannellini", "borlotti"],
    formaggiFreschi: ["ricotta", "robiola", "stracchino", "primo sale", "formaggio fresco", "fiocchi di latte"],
  },
  proteinFrequencyTargets: {
    carneRossa: { min: 1, max: 1 },
    carneBianca: { min: 2, max: 2 },
    pesce: { min: 2, max: 2 },
    uova: { min: 1, max: 2 },
    legumi: { min: 4, max: 5 },
    formaggiFreschi: { min: 1, max: 2 },
  },
  feedingStyleGuidance: {
    classico: [
      "Consentiti: puree, creme, passati, pastina, baby riso, porridge, yogurt, legumi decorticati ridotti a purea, alimenti frullati e creme.",
      "Non proporre polpette, burger, pancake, finger food, pane, torte, pezzi, consistenze troppo dense o formati troppo grandi.",
    ],
    autosvezzamento: [
      "Consentiti: porridge, polpette morbide, pancake, burger di carne con verdure nell'impasto, pane, torte morbide, formati piu grandi nei tagli sicuri adeguati.",
      "Offrire sempre nei tagli sicuri adeguati all'eta del bambino; privilegiare consistenze morbide, facili da afferrare e realistiche.",
    ],
    misto: [
      "Combinare davvero approccio classico e autosvezzamento nello stesso menu, mantenendo coerenza di sicurezza e consistenze.",
      "Includere sia proposte cremose/frullate del classico sia proposte morbide da autosvezzamento nei tagli sicuri.",
    ],
  },
  hardSafetyRules: [
    "Non proporre alimenti esclusi per allergie o intolleranze.",
    "Non usare sale aggiunto, zucchero aggiunto, dolcificanti, miele o alimenti a rischio soffocamento.",
    "Usare consistenze e tagli coerenti con l'età del bambino.",
    "Evitare preparazioni con rischio di soffocamento senza note di sicurezza.",
    "Per pranzo e cena rispettare il piatto bilanciato.",
    "Evitare suggerimenti medici: fornire sempre nota di confronto con pediatra in caso di dubbi.",
    "Preferire ricette semplici, ingredienti reperibili, pochi ingredienti e varianti pratiche.",
  ],
  outputConstraints: {
    maxIngredientsPerMeal: 12,
    maxNotesPerMeal: 5,
    maxSubstitutionsPerMeal: 4,
  },
};

export type MealType = (typeof businessRulesConfig.mealTypes)[number];
