export const businessRulesConfig = {
  mealTypes: ["colazione", "pranzo", "merenda", "cena"] as const,
  allowedFeedingStyles: ["classico", "autosvezzamento", "misto"] as const,
  ageStageRules: {
    under6: "Prima dei 6 mesi il focus resta sul latte; proporre solo indicazioni prudenti e confronto con pediatra.",
    from6To8: "Consistenze molto morbide: creme lisce, vellutate, alimenti schiacciati.",
    from8To10: "Progressione graduale: piccoli pezzi morbidi e facilmente gestibili.",
    from10To12: "Maggiore varietà mantenendo sicurezza, consistenze adatte e supervisione.",
    from12To24: "Pasti completi bilanciati e progressiva autonomia.",
    over24: "Composizione piatto aggiornata: 2/4 verdure, 1/4 carboidrati, 1/4 proteine + grassi buoni.",
  },
  balancedPlate: {
    under24Months: {
      carbsRatio: "2/4",
      proteinsRatio: "1/4",
      vegetablesRatio: "1/4",
      healthyFats: "olio extravergine d'oliva a crudo",
    },
    over24Months: {
      vegetablesRatio: "2/4",
      carbsRatio: "1/4",
      proteinsRatio: "1/4",
      healthyFats: "piccola quota di grassi buoni (olio extravergine d'oliva a crudo)",
    },
  },
  ingredientGroups: {
    carbs: [
      "pasta",
      "riso",
      "farro",
      "orzo",
      "avena",
      "miglio",
      "quinoa",
      "patata",
      "patate",
      "semolino",
      "cous cous",
    ],
    proteins: [
      "carne",
      "manzo",
      "pollo",
      "tacchino",
      "pesce",
      "salmone",
      "merluzzo",
      "uovo",
      "uova",
      "ricotta",
      "formaggio fresco",
      "robiola",
      "legumi",
      "lenticchie",
      "ceci",
      "piselli",
      "fagioli",
    ],
    vegetables: [
      "zucchine",
      "carote",
      "zucca",
      "broccoli",
      "cavolfiore",
      "bietola",
      "spinaci",
      "pomodoro",
      "pomodorini",
      "verdure",
      "fagiolini",
      "melanzane",
    ],
    healthyFats: ["olio evo", "olio extravergine", "olio extravergine d'oliva"],
  },
  forbidden: {
    always: [
      "sale aggiunto",
      "zucchero",
      "zuccheri aggiunti",
      "dolcificante",
      "dolcificanti",
      "miele",
      "caramelle",
      "popcorn",
      "frutta secca intera",
      "chicchi duri",
    ],
    chokingRisk: ["frutta secca intera", "popcorn", "caramelle", "chicchi duri"],
    roundFoods: ["uva", "pomodorini"],
    cylindricalFoods: ["carota", "carote", "zucchina", "zucchine"],
    hardFoods: ["mela cruda", "carota cruda"],
  },
  safeCutRules: [
    "I cibi tondi vanno proposti in quarti/spicchi (es. uva, pomodorini).",
    "I cibi cilindrici vanno proposti a bastoncino o in taglio longitudinale (es. carote, zucchine).",
    "I cibi duri vanno cotti, grattugiati o ridotti in crema (es. mela cruda, carota cruda).",
  ],
  proteinFrequencyWeekly: {
    carne: "2-3 volte a settimana",
    pesce: "2 volte a settimana",
    uova: "1-2 volte a settimana",
    legumi: "3-4 volte a settimana",
    formaggiFreschi: "1-2 volte a settimana",
  },
  proteinCategoryKeywords: {
    carne: ["carne", "manzo", "vitello", "pollo", "tacchino", "maiale", "coniglio"],
    pesce: ["pesce", "salmone", "merluzzo", "orata", "platessa", "trota", "nasello"],
    uova: ["uovo", "uova", "frittata"],
    legumi: ["legumi", "lenticchie", "ceci", "piselli", "fagioli", "cannellini", "borlotti"],
    formaggiFreschi: ["ricotta", "robiola", "stracchino", "primo sale", "formaggio fresco", "fiocchi di latte"],
  },
  proteinFrequencyTargets: {
    carne: { min: 2, max: 3 },
    pesce: { min: 2, max: 2 },
    uova: { min: 1, max: 2 },
    legumi: { min: 3, max: 4 },
    formaggiFreschi: { min: 1, max: 2 },
  },
  feedingStyleGuidance: {
    classico: [
      "Progressione consistenze: crema liscia, piccoli granuli, morbido schiacciato, piccoli pezzi.",
      "Pappa tipica: crema cereali + brodo vegetale + verdure + proteine + olio EVO.",
    ],
    autosvezzamento: [
      "Prediligere pezzi morbidi, facili da afferrare e in forma sicura.",
      "Esempi coerenti: bastoncini, polpette morbide, frittate, pancake, pasta corta.",
    ],
    misto: ["Combinare approccio classico e autosvezzamento mantenendo coerenza di sicurezza e consistenze."],
  },
  hardSafetyRules: [
    "Non proporre alimenti esclusi per allergie o intolleranze.",
    "Non usare sale aggiunto, zucchero aggiunto, dolcificanti, miele o alimenti a rischio soffocamento.",
    "Usare consistenze e tagli coerenti con l'età del bambino.",
    "Evitare preparazioni con rischio di soffocamento senza note di sicurezza.",
    "Per pranzo e cena rispettare il piatto bilanciato.",
    "Evitare suggerimenti medici: fornire sempre nota di confronto con pediatra in caso di dubbi.",
    "Preferire ricette semplici, ingredienti reperibili, pochi ingredienti e varianti pratiche.",
  ],
  outputConstraints: {
    maxIngredientsPerMeal: 12,
    maxNotesPerMeal: 5,
    maxSubstitutionsPerMeal: 4,
  },
};

export type MealType = (typeof businessRulesConfig.mealTypes)[number];
